# Converting Data to CSV for Tableau
## 01. Import Libraries

In [1]:
import pandas as pd
import numpy as np
import os

## 02. Data

In [2]:
df = pd.read_pickle(r"C:\Users\jmanc\OneDrive\Desktop\F1 Project\Data\Prepped Data\race_lap_full.pkl")
df.head(10)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,code,forename,surname,nationality,lap_num,lap_pos,lap_time,lap_milli,status,year
0,22131,900,825,1,20,4,2.0,2,2,18.0,...,MAG,Kevin,Magnussen,Danish,1,3,01:45.4,105402,Finished,2014
1,22131,900,825,1,20,4,2.0,2,2,18.0,...,MAG,Kevin,Magnussen,Danish,2,3,01:37.4,97435,Finished,2014
2,22131,900,825,1,20,4,2.0,2,2,18.0,...,MAG,Kevin,Magnussen,Danish,3,3,01:37.9,97917,Finished,2014
3,22131,900,825,1,20,4,2.0,2,2,18.0,...,MAG,Kevin,Magnussen,Danish,4,3,01:36.8,96796,Finished,2014
4,22131,900,825,1,20,4,2.0,2,2,18.0,...,MAG,Kevin,Magnussen,Danish,5,3,01:36.8,96766,Finished,2014
5,22131,900,825,1,20,4,2.0,2,2,18.0,...,MAG,Kevin,Magnussen,Danish,6,3,01:35.9,95857,Finished,2014
6,22131,900,825,1,20,4,2.0,2,2,18.0,...,MAG,Kevin,Magnussen,Danish,7,3,01:35.4,95446,Finished,2014
7,22131,900,825,1,20,4,2.0,2,2,18.0,...,MAG,Kevin,Magnussen,Danish,8,3,01:35.8,95752,Finished,2014
8,22131,900,825,1,20,4,2.0,2,2,18.0,...,MAG,Kevin,Magnussen,Danish,9,3,01:35.7,95740,Finished,2014
9,22131,900,825,1,20,4,2.0,2,2,18.0,...,MAG,Kevin,Magnussen,Danish,10,3,01:35.6,95555,Finished,2014

In [3]:
df.shape

(206419, 31)

## 03. Export to CSV

In [5]:
df.to_csv(r"C:\Users\jmanc\OneDrive\Desktop\F1 Project\Data\Prepped Data\race_lap_full.csv")